apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: github-machine-user-ssh-private-key
  namespace: argocd
spec:
  data:
    - remoteRef:
        key: /github/machine-user/ssh-private-key
      secretKey: sshPrivateKey
