apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://charts.external-secrets.io"
    targetRevision: 0.5.6
    chart: external-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: for-cluster-secret-store
  namespace: external-secrets
---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: for-cluster-secret-store
            namespace: external-secrets
