# https://github.com/stakater/Reloader#helm-charts
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://stakater.github.io/stakater-charts"
    targetRevision: v1.0.4
    chart: reloader
  destination:
    server: "https://kubernetes.default.svc"
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
