apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: rails-app
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: parameter-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - remoteRef:
        key: /eks-rails/rails/rails-master-key
      secretKey: RAILS_MASTER_KEY
    - remoteRef:
        key: /eks-rails/rds/master-username
      secretKey: DATABASE_USERNAME
    - remoteRef:
        key: /eks-rails/rds/master-password
      secretKey: DATABASE_PASSWORD
    - remoteRef:
        key: /eks-rails/rds/endpoint
      secretKey: DATABASE_HOST
    - remoteRef:
        key: /eks-rails/rds/port
      secretKey: DATABASE_PORT
