resources:
- deployment.yaml
- env-configmap.yaml
- external-secret.yaml
- ingress.yaml
- service-account.yaml
- service.yaml
- pdb.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
