apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  # ↓ argocd自身を管理する特殊性を鑑みてfinalizeは無効化しておく
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  source:
    helm:
      parameters:
        - name: "server.config.url"
          value: "https://argo-cd.danimal141.com"
        - name: "server.ingress.hosts[0]"
          value: "argocd.danimal141.com"
        - name: "server.ingress.annotations.alb\\.ingress\\.kubernetes\\.io/certificate-arn"
          value: "arn:aws:acm:ap-northeast-1:REPLACE_YOUR_AWS_ACCOUNT_ID:certificate/3faecdc4-4008-4ea6-9504-af5e937dbf47"
