apiVersion: v1
kind: ServiceAccount
metadata:
  name: for-cluster-secret-store
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::REPLACE_YOUR_AWS_ACCOUNT_ID:role/external-secrets-operator"
