apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    helm:
      parameters:
        - name: "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
          value: "arn:aws:iam::REPLACE_YOUR_AWS_ACCOUNT_ID:role/external-dns"
